FROM python:3.9

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY recv_log_topic.py .

CMD ["sh", "-c", "python3 recv_log_topic.py '#' & tail -f /dev/null"]
