global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.89.170:9100']
  - job_name: 'RabbitMQ'
    metrics_path: "/metrics"
    static_configs:
      - targets: ['rabbitmq-1:15692']
      - targets: ['rabbitmq-2:15692']
      - targets: ['rabbitmq-3:15692']
  - job_name: 'Docker'
    static_configs:
      - targets: ['192.168.89.170:9323']